$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: es-model-endpoint
model: azureml:es_logreg_model:1
code_configuration:
  code: .
  scoring_script: score.py
environment:
  name: es-inference-env
  version: "1"
  conda_file: conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS2_v2
instance_count: 1
